import {
  LayoutDashboard, Play, GitBranch, Globe, Clock, Bell, Flag, CircleDot,
  UserCheck, Shield, FileJson, Download, Upload, History, Copy, Archive,
  RotateCcw, PlayCircle, PauseCircle, StopCircle, RefreshCw, SkipForward,
  Workflow, Variable, Key, Link,
  // New icons for expanded node types
  Calendar, Webhook, Zap, QrCode, SquareMenu, Ban, XCircle, AlertTriangle,
  ExternalLink, ArrowLeftRight, Maximize2, PanelRight, Columns2, CornerDownLeft,
  LogIn, LogOut, ShieldCheck, KeyRound, Fingerprint, UserCog, LockKeyhole,
  GitFork, ToggleLeft, Hash, Binary, FileCode, Users, Activity, CalendarDays, Type, Regex,
  Repeat, Timer, TimerOff,
  Database, FilePlus, FileEdit, FileX, Search, FileUp, FileDown, FileText, Sheet, Printer,
  Send, MessageSquare, Mail, Smartphone, MessageCircle, BellRing,
  FormInput, List, CheckSquare, Radio, CalendarPlus, PenTool,
  Boxes, Container, StickyNote, MessageSquareDashed,
  Server, HardDrive, Plug,
} from 'lucide-react';

// ─────────────────────────────────────────────────
// NODE TYPES — 35+ Professional Workflow Node Types
// ─────────────────────────────────────────────────

export const NODE_TYPES = {
  // ── Trigger Nodes ──────────────────────────────
  start: {
    type: 'start',
    label: 'Start',
    icon: Play,
    color: '#22c55e',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    description: 'Manual flow entry point',
    category: 'triggers',
    defaultConfig: {},
  },
  trigger_schedule: {
    type: 'trigger_schedule',
    label: 'Schedule',
    icon: Calendar,
    color: '#22c55e',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    description: 'Trigger on schedule (cron)',
    category: 'triggers',
    defaultConfig: { cronExpression: '', timezone: 'UTC' },
  },
  trigger_webhook: {
    type: 'trigger_webhook',
    label: 'Webhook',
    icon: Webhook,
    color: '#22c55e',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    description: 'Trigger via webhook URL',
    category: 'triggers',
    defaultConfig: { method: 'POST', path: '' },
  },
  trigger_event: {
    type: 'trigger_event',
    label: 'Event',
    icon: Zap,
    color: '#22c55e',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    description: 'Trigger on system event',
    category: 'triggers',
    defaultConfig: { eventName: '', eventSource: '' },
  },
  trigger_deeplink: {
    type: 'trigger_deeplink',
    label: 'Deep Link',
    icon: Link,
    color: '#22c55e',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    description: 'Trigger via deep link',
    category: 'triggers',
    defaultConfig: { path: '', params: {} },
  },
  trigger_qrscan: {
    type: 'trigger_qrscan',
    label: 'QR Scan',
    icon: QrCode,
    color: '#22c55e',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    description: 'Trigger on QR code scan',
    category: 'triggers',
    defaultConfig: { expectedFormat: '' },
  },
  trigger_module: {
    type: 'trigger_module',
    label: 'Module Entry',
    icon: SquareMenu,
    color: '#22c55e',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    description: 'Trigger when entering a module',
    category: 'triggers',
    defaultConfig: { moduleName: '' },
  },

  // ── End State Nodes ────────────────────────────
  end: {
    type: 'end',
    label: 'End',
    icon: Flag,
    color: '#64748b',
    bgColor: 'bg-slate-500/10',
    borderColor: 'border-slate-500/30',
    description: 'Flow completion',
    category: 'end_states',
    defaultConfig: {},
  },
  end_success: {
    type: 'end_success',
    label: 'Success',
    icon: CircleDot,
    color: '#22c55e',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    description: 'Flow completed successfully',
    category: 'end_states',
    defaultConfig: { message: 'Completed successfully' },
  },
  end_failure: {
    type: 'end_failure',
    label: 'Failure',
    icon: XCircle,
    color: '#ef4444',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    description: 'Flow failed',
    category: 'end_states',
    defaultConfig: { errorMessage: '', errorCode: '' },
  },
  end_cancel: {
    type: 'end_cancel',
    label: 'Cancel',
    icon: Ban,
    color: '#f59e0b',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    description: 'Flow cancelled',
    category: 'end_states',
    defaultConfig: { reason: '' },
  },
  end_terminate: {
    type: 'end_terminate',
    label: 'Terminate',
    icon: AlertTriangle,
    color: '#ef4444',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    description: 'Force terminate flow',
    category: 'end_states',
    defaultConfig: {},
  },

  // ── Navigation Nodes ───────────────────────────
  page: {
    type: 'page',
    label: 'Page',
    icon: LayoutDashboard,
    color: '#3b82f6',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    description: 'Navigate to a page',
    category: 'navigation',
    defaultConfig: { page: '' },
  },
  navigate: {
    type: 'navigate',
    label: 'Navigate',
    icon: ExternalLink,
    color: '#3b82f6',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    description: 'Navigate to URL or route',
    category: 'navigation',
    defaultConfig: { url: '', openInNewTab: false },
  },
  redirect: {
    type: 'redirect',
    label: 'Redirect',
    icon: ArrowLeftRight,
    color: '#3b82f6',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    description: 'Redirect to another route',
    category: 'navigation',
    defaultConfig: { to: '', replace: true },
  },
  open_modal: {
    type: 'open_modal',
    label: 'Open Modal',
    icon: Maximize2,
    color: '#3b82f6',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    description: 'Open a modal dialog',
    category: 'navigation',
    defaultConfig: { modalId: '', title: '', size: 'md' },
  },
  open_drawer: {
    type: 'open_drawer',
    label: 'Open Drawer',
    icon: PanelRight,
    color: '#3b82f6',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    description: 'Open a side drawer',
    category: 'navigation',
    defaultConfig: { drawerId: '', position: 'right' },
  },
  open_tab: {
    type: 'open_tab',
    label: 'Open Tab',
    icon: Columns2,
    color: '#3b82f6',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    description: 'Open in new tab',
    category: 'navigation',
    defaultConfig: { tabId: '', url: '' },
  },
  return_back: {
    type: 'return_back',
    label: 'Return',
    icon: CornerDownLeft,
    color: '#3b82f6',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    description: 'Return to previous page',
    category: 'navigation',
    defaultConfig: { fallbackUrl: '/' },
  },

  // ── Authentication Nodes ───────────────────────
  auth_login: {
    type: 'auth_login',
    label: 'Login',
    icon: LogIn,
    color: '#10b981',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    description: 'Authenticate user login',
    category: 'authentication',
    defaultConfig: { method: 'credentials', redirectOnSuccess: '/dashboard' },
  },
  auth_logout: {
    type: 'auth_logout',
    label: 'Logout',
    icon: LogOut,
    color: '#10b981',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    description: 'Logout current user',
    category: 'authentication',
    defaultConfig: { redirectTo: '/login', clearStorage: true },
  },
  auth_validate_token: {
    type: 'auth_validate_token',
    label: 'Validate Token',
    icon: ShieldCheck,
    color: '#10b981',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    description: 'Validate JWT token',
    category: 'authentication',
    defaultConfig: { tokenSource: 'cookie' },
  },
  auth_otp: {
    type: 'auth_otp',
    label: 'OTP',
    icon: KeyRound,
    color: '#10b981',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    description: 'OTP verification',
    category: 'authentication',
    defaultConfig: { method: 'email', length: 6, expiry: 300 },
  },
  auth_mfa: {
    type: 'auth_mfa',
    label: 'MFA',
    icon: Fingerprint,
    color: '#10b981',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    description: 'Multi-factor authentication',
    category: 'authentication',
    defaultConfig: { factors: ['otp'] },
  },
  auth_role_check: {
    type: 'auth_role_check',
    label: 'Role Check',
    icon: UserCog,
    color: '#10b981',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    description: 'Validate user role',
    category: 'authentication',
    defaultConfig: { allowedRoles: ['admin'], denyRedirect: '/unauthorized' },
  },
  auth_permission_check: {
    type: 'auth_permission_check',
    label: 'Permission Check',
    icon: LockKeyhole,
    color: '#10b981',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    description: 'Check user permissions',
    category: 'authentication',
    defaultConfig: { permission: '', resource: '' },
  },

  // ── Condition Nodes ────────────────────────────
  decision: {
    type: 'decision',
    label: 'If / Else',
    icon: GitBranch,
    color: '#ef4444',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    description: 'Conditional branching',
    category: 'conditions',
    defaultConfig: { condition: '', conditionExpression: '' },
    handles: { sources: ['yes', 'no'] },
  },
  condition_switch: {
    type: 'condition_switch',
    label: 'Switch',
    icon: GitFork,
    color: '#ef4444',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    description: 'Multi-way branching',
    category: 'conditions',
    defaultConfig: { switchExpression: '', cases: [{ label: 'Case 1', value: '' }], defaultCase: true },
    handles: { sources: ['dynamic'] },
  },
  condition_expression: {
    type: 'condition_expression',
    label: 'Expression',
    icon: FileCode,
    color: '#ef4444',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    description: 'Custom JS expression',
    category: 'conditions',
    defaultConfig: { expression: '' },
    handles: { sources: ['true', 'false'] },
  },
  condition_role: {
    type: 'condition_role',
    label: 'Check Role',
    icon: Users,
    color: '#ef4444',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    description: 'Branch by user role',
    category: 'conditions',
    defaultConfig: { roles: {} },
    handles: { sources: ['dynamic'] },
  },
  condition_user_type: {
    type: 'condition_user_type',
    label: 'User Type',
    icon: UserCheck,
    color: '#ef4444',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    description: 'Branch by user type',
    category: 'conditions',
    defaultConfig: { userTypes: [] },
    handles: { sources: ['dynamic'] },
  },
  condition_status: {
    type: 'condition_status',
    label: 'Check Status',
    icon: Activity,
    color: '#ef4444',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    description: 'Branch by status value',
    category: 'conditions',
    defaultConfig: { field: '', values: [] },
    handles: { sources: ['dynamic'] },
  },

  // ── Loop Nodes ─────────────────────────────────
  loop_foreach: {
    type: 'loop_foreach',
    label: 'For Each',
    icon: Repeat,
    color: '#f97316',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    description: 'Iterate over a collection',
    category: 'loops',
    defaultConfig: { collection: '', itemVariable: 'item', indexVariable: 'index' },
    handles: { sources: ['loop_body', 'done'] },
  },
  loop_while: {
    type: 'loop_while',
    label: 'While',
    icon: RefreshCw,
    color: '#f97316',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    description: 'Loop while condition is true',
    category: 'loops',
    defaultConfig: { condition: '', maxIterations: 100 },
    handles: { sources: ['loop_body', 'done'] },
  },
  loop_repeat: {
    type: 'loop_repeat',
    label: 'Repeat',
    icon: RotateCcw,
    color: '#f97316',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    description: 'Repeat N times',
    category: 'loops',
    defaultConfig: { count: 3, counterVariable: 'i' },
    handles: { sources: ['loop_body', 'done'] },
  },

  // ── Data Operation Nodes ───────────────────────
  action: {
    type: 'action',
    label: 'Action',
    icon: Play,
    color: '#f59e0b',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    description: 'Run an internal action',
    category: 'operations',
    defaultConfig: { action: '', actionParams: {} },
  },
  data_create: {
    type: 'data_create',
    label: 'Create Record',
    icon: FilePlus,
    color: '#8b5cf6',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    description: 'Create a new record',
    category: 'operations',
    defaultConfig: { collection: '', data: {} },
  },
  data_update: {
    type: 'data_update',
    label: 'Update Record',
    icon: FileEdit,
    color: '#8b5cf6',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    description: 'Update an existing record',
    category: 'operations',
    defaultConfig: { collection: '', filter: {}, data: {} },
  },
  data_delete: {
    type: 'data_delete',
    label: 'Delete Record',
    icon: FileX,
    color: '#8b5cf6',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    description: 'Delete a record',
    category: 'operations',
    defaultConfig: { collection: '', filter: {} },
  },
  data_fetch: {
    type: 'data_fetch',
    label: 'Fetch Record',
    icon: Search,
    color: '#8b5cf6',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    description: 'Fetch records from database',
    category: 'operations',
    defaultConfig: { collection: '', filter: {}, limit: 20, sort: {} },
  },
  data_upload: {
    type: 'data_upload',
    label: 'Upload File',
    icon: FileUp,
    color: '#8b5cf6',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    description: 'Upload a file',
    category: 'operations',
    defaultConfig: { destination: '', maxSize: '10mb', allowedTypes: [] },
  },
  data_download: {
    type: 'data_download',
    label: 'Download File',
    icon: FileDown,
    color: '#8b5cf6',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    description: 'Download a file',
    category: 'operations',
    defaultConfig: { fileUrl: '', filename: '' },
  },
  data_generate_pdf: {
    type: 'data_generate_pdf',
    label: 'Generate PDF',
    icon: FileText,
    color: '#8b5cf6',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    description: 'Generate a PDF document',
    category: 'operations',
    defaultConfig: { template: '', data: {} },
  },
  data_export_csv: {
    type: 'data_export_csv',
    label: 'Export CSV',
    icon: Sheet,
    color: '#8b5cf6',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    description: 'Export data as CSV',
    category: 'operations',
    defaultConfig: { columns: [], data: '' },
  },
  data_print: {
    type: 'data_print',
    label: 'Print',
    icon: Printer,
    color: '#8b5cf6',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    description: 'Print document or page',
    category: 'operations',
    defaultConfig: { target: '' },
  },

  // ── API Nodes ──────────────────────────────────
  api: {
    type: 'api',
    label: 'API Call',
    icon: Globe,
    color: '#8b5cf6',
    bgColor: 'bg-purple-500/10',
    borderColor: 'border-purple-500/30',
    description: 'Execute HTTP API call',
    category: 'api',
    defaultConfig: { apiEndpoint: '', apiMethod: 'GET', apiHeaders: {}, apiBody: {}, retry: 0, timeout: 30000 },
  },

  // ── Timing Nodes ───────────────────────────────
  delay: {
    type: 'delay',
    label: 'Delay',
    icon: Clock,
    color: '#06b6d4',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    description: 'Wait before proceeding',
    category: 'timing',
    defaultConfig: { delay: 5, delayUnit: 'seconds' },
  },

  // ── Notification Nodes ─────────────────────────
  notification: {
    type: 'notification',
    label: 'Notification',
    icon: Bell,
    color: '#ec4899',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    description: 'Send notification',
    category: 'communication',
    defaultConfig: { notificationType: 'toast', notificationTitle: '', notificationMessage: '', notificationRecipients: [] },
  },
  notification_email: {
    type: 'notification_email',
    label: 'Send Email',
    icon: Mail,
    color: '#ec4899',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    description: 'Send an email',
    category: 'communication',
    defaultConfig: { to: '', subject: '', body: '', template: '' },
  },
  notification_sms: {
    type: 'notification_sms',
    label: 'Send SMS',
    icon: Smartphone,
    color: '#ec4899',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    description: 'Send an SMS message',
    category: 'communication',
    defaultConfig: { to: '', message: '' },
  },
  notification_whatsapp: {
    type: 'notification_whatsapp',
    label: 'WhatsApp',
    icon: MessageCircle,
    color: '#22c55e',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    description: 'Send WhatsApp message',
    category: 'communication',
    defaultConfig: { to: '', template: '', message: '' },
  },
  notification_push: {
    type: 'notification_push',
    label: 'Push Notification',
    icon: BellRing,
    color: '#ec4899',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    description: 'Send push notification',
    category: 'communication',
    defaultConfig: { title: '', body: '', icon: '', target: 'all' },
  },

  // ── Form Nodes ─────────────────────────────────
  form_input: {
    type: 'form_input',
    label: 'Input Field',
    icon: FormInput,
    color: '#14b8a6',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/30',
    description: 'Text input field',
    category: 'forms',
    defaultConfig: { fieldName: '', fieldType: 'text', placeholder: '', required: true, validation: '' },
  },
  form_dropdown: {
    type: 'form_dropdown',
    label: 'Dropdown',
    icon: List,
    color: '#14b8a6',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/30',
    description: 'Dropdown select field',
    category: 'forms',
    defaultConfig: { fieldName: '', options: [], multiple: false, required: true },
  },
  form_checkbox: {
    type: 'form_checkbox',
    label: 'Checkbox',
    icon: CheckSquare,
    color: '#14b8a6',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/30',
    description: 'Checkbox input',
    category: 'forms',
    defaultConfig: { fieldName: '', label: '', defaultChecked: false },
  },
  form_upload: {
    type: 'form_upload',
    label: 'File Upload',
    icon: Upload,
    color: '#14b8a6',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/30',
    description: 'File upload field',
    category: 'forms',
    defaultConfig: { fieldName: '', accept: '', maxSize: '5mb', multiple: false },
  },
  form_date: {
    type: 'form_date',
    label: 'Date Picker',
    icon: CalendarPlus,
    color: '#14b8a6',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/30',
    description: 'Date picker field',
    category: 'forms',
    defaultConfig: { fieldName: '', format: 'yyyy-MM-dd', minDate: '', maxDate: '' },
  },
  form_signature: {
    type: 'form_signature',
    label: 'Signature',
    icon: PenTool,
    color: '#14b8a6',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/30',
    description: 'Signature capture',
    category: 'forms',
    defaultConfig: { fieldName: '', required: true },
  },

  // ── Integration Nodes ──────────────────────────
  integration_internal_api: {
    type: 'integration_internal_api',
    label: 'Internal API',
    icon: Server,
    color: '#6366f1',
    bgColor: 'bg-indigo-500/10',
    borderColor: 'border-indigo-500/30',
    description: 'Call internal API endpoint',
    category: 'integrations',
    defaultConfig: { service: '', endpoint: '', method: 'GET' },
  },
  integration_database: {
    type: 'integration_database',
    label: 'Database',
    icon: Database,
    color: '#6366f1',
    bgColor: 'bg-indigo-500/10',
    borderColor: 'border-indigo-500/30',
    description: 'Direct database operation',
    category: 'integrations',
    defaultConfig: { operation: 'find', collection: '', query: {} },
  },
  integration_storage: {
    type: 'integration_storage',
    label: 'Storage',
    icon: HardDrive,
    color: '#6366f1',
    bgColor: 'bg-indigo-500/10',
    borderColor: 'border-indigo-500/30',
    description: 'Cloud storage operation',
    category: 'integrations',
    defaultConfig: { provider: 'cloudinary', operation: 'upload' },
  },

  // ── Utility Nodes ──────────────────────────────
  comment: {
    type: 'comment',
    label: 'Comment',
    icon: MessageSquareDashed,
    color: '#94a3b8',
    bgColor: 'bg-slate-400/10',
    borderColor: 'border-slate-400/30',
    description: 'Add a canvas comment',
    category: 'utility',
    defaultConfig: { text: '' },
    isUtility: true,
  },
  sticky_note: {
    type: 'sticky_note',
    label: 'Sticky Note',
    icon: StickyNote,
    color: '#fbbf24',
    bgColor: 'bg-yellow-400/10',
    borderColor: 'border-yellow-400/30',
    description: 'Sticky note annotation',
    category: 'utility',
    defaultConfig: { text: '', color: '#fef3c7' },
    isUtility: true,
  },
  group: {
    type: 'group',
    label: 'Group',
    icon: Boxes,
    color: '#a78bfa',
    bgColor: 'bg-violet-400/10',
    borderColor: 'border-violet-400/30',
    description: 'Group related nodes',
    category: 'utility',
    defaultConfig: { label: 'Group', color: '#a78bfa', collapsed: false },
    isUtility: true,
  },
};

// ─────────────────────────────────────────────────
// NODE CATEGORIES — Organized groupings
// ─────────────────────────────────────────────────

export const NODE_CATEGORIES = [
  {
    label: 'Triggers',
    key: 'triggers',
    icon: Zap,
    types: ['start', 'trigger_schedule', 'trigger_webhook', 'trigger_event', 'trigger_deeplink', 'trigger_qrscan', 'trigger_module'],
  },
  {
    label: 'End States',
    key: 'end_states',
    icon: Flag,
    types: ['end', 'end_success', 'end_failure', 'end_cancel', 'end_terminate'],
  },
  {
    label: 'Navigation',
    key: 'navigation',
    icon: ExternalLink,
    types: ['page', 'navigate', 'redirect', 'open_modal', 'open_drawer', 'open_tab', 'return_back'],
  },
  {
    label: 'Authentication',
    key: 'authentication',
    icon: Shield,
    types: ['auth_login', 'auth_logout', 'auth_validate_token', 'auth_otp', 'auth_mfa', 'auth_role_check', 'auth_permission_check'],
  },
  {
    label: 'Conditions',
    key: 'conditions',
    icon: GitBranch,
    types: ['decision', 'condition_switch', 'condition_expression', 'condition_role', 'condition_user_type', 'condition_status'],
  },
  {
    label: 'Loops',
    key: 'loops',
    icon: Repeat,
    types: ['loop_foreach', 'loop_while', 'loop_repeat'],
  },
  {
    label: 'Data Operations',
    key: 'operations',
    icon: Database,
    types: ['action', 'data_create', 'data_update', 'data_delete', 'data_fetch', 'data_upload', 'data_download', 'data_generate_pdf', 'data_export_csv', 'data_print'],
  },
  {
    label: 'API',
    key: 'api',
    icon: Globe,
    types: ['api'],
  },
  {
    label: 'Timing',
    key: 'timing',
    icon: Clock,
    types: ['delay'],
  },
  {
    label: 'Communication',
    key: 'communication',
    icon: Bell,
    types: ['notification', 'notification_email', 'notification_sms', 'notification_whatsapp', 'notification_push'],
  },
  {
    label: 'Forms',
    key: 'forms',
    icon: FormInput,
    types: ['form_input', 'form_dropdown', 'form_checkbox', 'form_upload', 'form_date', 'form_signature'],
  },
  {
    label: 'Integrations',
    key: 'integrations',
    icon: Plug,
    types: ['integration_internal_api', 'integration_database', 'integration_storage'],
  },
  {
    label: 'Utility',
    key: 'utility',
    icon: StickyNote,
    types: ['comment', 'sticky_note', 'group'],
  },
];

// ─────────────────────────────────────────────────
// Determine input/output handles for each node type
// ─────────────────────────────────────────────────

/** Check if a node type has an input handle */
export const hasInputHandle = (nodeType) => {
  const triggers = ['start', 'trigger_schedule', 'trigger_webhook', 'trigger_event', 'trigger_deeplink', 'trigger_qrscan', 'trigger_module'];
  const utilities = ['comment', 'sticky_note', 'group'];
  return !triggers.includes(nodeType) && !utilities.includes(nodeType);
};

/** Check if a node type has output handle(s) */
export const hasOutputHandle = (nodeType) => {
  const endStates = ['end', 'end_success', 'end_failure', 'end_cancel', 'end_terminate'];
  const utilities = ['comment', 'sticky_note', 'group'];
  return !endStates.includes(nodeType) && !utilities.includes(nodeType);
};

/** Get the source handles for a node (for decision/switch/loop nodes) */
export const getSourceHandles = (nodeType) => {
  const config = NODE_TYPES[nodeType];
  if (config?.handles?.sources) {
    if (config.handles.sources.includes('dynamic')) return null; // dynamic handles
    return config.handles.sources;
  }
  return ['default'];
};

// ─────────────────────────────────────────────────
// EXISTING EXPORTS — Preserved unchanged
// ─────────────────────────────────────────────────

export const FLOW_STATUSES = [
  { value: 'draft', label: 'Draft', color: 'text-yellow-500', bgColor: 'bg-yellow-500/10' },
  { value: 'active', label: 'Active', color: 'text-green-500', bgColor: 'bg-green-500/10' },
  { value: 'archived', label: 'Archived', color: 'text-slate-500', bgColor: 'bg-slate-500/10' },
  { value: 'inactive', label: 'Inactive', color: 'text-red-500', bgColor: 'bg-red-500/10' },
];

export const EXECUTION_STATUSES = [
  { value: 'pending', label: 'Pending', color: 'text-yellow-500' },
  { value: 'running', label: 'Running', color: 'text-blue-500' },
  { value: 'paused', label: 'Paused', color: 'text-orange-500' },
  { value: 'completed', label: 'Completed', color: 'text-green-500' },
  { value: 'failed', label: 'Failed', color: 'text-red-500' },
  { value: 'cancelled', label: 'Cancelled', color: 'text-slate-500' },
];

export const ENTRY_POINTS = [
  { value: 'button_click', label: 'Button Click', icon: CircleDot },
  { value: 'menu', label: 'Menu', icon: LayoutDashboard },
  { value: 'sidebar', label: 'Sidebar', icon: LayoutDashboard },
  { value: 'api', label: 'API', icon: Globe },
  { value: 'login', label: 'Login', icon: UserCheck },
  { value: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { value: 'user_action', label: 'User Action', icon: Play },
  { value: 'deep_link', label: 'Deep Link', icon: Link },
  { value: 'qr_code', label: 'QR Code', icon: LayoutDashboard },
  { value: 'manual', label: 'Manual Start', icon: PlayCircle },
  { value: 'schedule', label: 'Schedule', icon: Calendar },
  { value: 'webhook', label: 'Webhook', icon: Webhook },
  { value: 'event', label: 'Event', icon: Zap },
  { value: 'module_entry', label: 'Module Entry', icon: SquareMenu },
];

export const ACTION_OPTIONS = [
  { value: 'create_student', label: 'Create Student' },
  { value: 'delete_user', label: 'Delete User' },
  { value: 'generate_report', label: 'Generate Report' },
  { value: 'export_csv', label: 'Export CSV' },
  { value: 'assign_teacher', label: 'Assign Teacher' },
  { value: 'upload_file', label: 'Upload File' },
  { value: 'send_email', label: 'Send Email' },
  { value: 'create_user', label: 'Create User' },
  { value: 'assign_role', label: 'Assign Role' },
  { value: 'update_profile', label: 'Update Profile' },
  { value: 'approve_request', label: 'Approve Request' },
  { value: 'reject_request', label: 'Reject Request' },
  { value: 'mark_attendance', label: 'Mark Attendance' },
  { value: 'process_fee', label: 'Process Fee' },
  { value: 'publish_result', label: 'Publish Result' },
  { value: 'send_notification', label: 'Send Notification' },
];

export const PAGE_OPTIONS = [
  { value: 'dashboard', label: 'Dashboard' },
  { value: 'students', label: 'Student Details' },
  { value: 'attendance', label: 'Attendance' },
  { value: 'fee', label: 'Fee' },
  { value: 'reports', label: 'Reports' },
  { value: 'settings', label: 'Settings' },
  { value: 'projects', label: 'Projects' },
  { value: 'users', label: 'User Management' },
  { value: 'admission', label: 'Admission' },
  { value: 'leaves', label: 'Leave Management' },
  { value: 'results', label: 'Results' },
  { value: 'timetable', label: 'Timetable' },
];

export const NOTIFICATION_OPTIONS = [
  { value: 'toast', label: 'Toast', icon: Bell },
  { value: 'alert', label: 'Alert', icon: Bell },
  { value: 'email', label: 'Email', icon: Mail },
  { value: 'sms', label: 'SMS', icon: Smartphone },
  { value: 'push', label: 'Push Notification', icon: BellRing },
  { value: 'whatsapp', label: 'WhatsApp', icon: MessageCircle },
  { value: 'browser', label: 'Browser Notification', icon: Bell },
];

export const DELAY_OPTIONS = [
  { value: 'seconds', label: 'Seconds' },
  { value: 'minutes', label: 'Minutes' },
  { value: 'hours', label: 'Hours' },
  { value: 'days', label: 'Days' },
];

export const ROLES = [
  { value: 'super_admin', label: 'Super Admin' },
  { value: 'admin', label: 'Admin' },
  { value: 'teacher', label: 'Teacher' },
  { value: 'student', label: 'Student' },
  { value: 'parent', label: 'Parent' },
  { value: 'guest', label: 'Guest' },
];

export const VARIABLE_TYPES = [
  { value: 'string', label: 'String' },
  { value: 'number', label: 'Number' },
  { value: 'boolean', label: 'Boolean' },
  { value: 'date', label: 'Date' },
  { value: 'object', label: 'Object' },
  { value: 'array', label: 'Array' },
  { value: 'expression', label: 'Expression' },
];

export const VARIABLE_SCOPES = [
  { value: 'global', label: 'Global' },
  { value: 'session', label: 'Session' },
  { value: 'local', label: 'Local' },
  { value: 'input', label: 'Input' },
  { value: 'output', label: 'Output' },
  { value: 'environment', label: 'Environment' },
  { value: 'temporary', label: 'Temporary' },
];

export const TEMPLATE_CATEGORIES = [
  { value: 'admin', label: 'Admin' },
  { value: 'student', label: 'Student' },
  { value: 'parent', label: 'Parent' },
  { value: 'teacher', label: 'Teacher' },
  { value: 'admission', label: 'Admission' },
  { value: 'attendance', label: 'Attendance' },
  { value: 'fee', label: 'Fee Collection' },
  { value: 'leave', label: 'Leave Approval' },
  { value: 'result', label: 'Result Publishing' },
  { value: 'assignment', label: 'Assignment Submission' },
  { value: 'report', label: 'Report Generation' },
  { value: 'notification', label: 'Notifications' },
  { value: 'approval', label: 'Approval' },
  { value: 'onboarding', label: 'Onboarding' },
  { value: 'general', label: 'General' },
];

export const FLOW_SORT_OPTIONS = [
  { value: 'updatedAt', label: 'Last Updated' },
  { value: 'createdAt', label: 'Created' },
  { value: 'name', label: 'Name' },
  { value: 'status', label: 'Status' },
];

// ─────────────────────────────────────────────────
// MODULE LINKING TARGETS — for workflow-module linking
// ─────────────────────────────────────────────────

export const MODULE_LINK_TARGETS = [
  { value: 'page', label: 'Page' },
  { value: 'button', label: 'Button' },
  { value: 'sidebar', label: 'Sidebar Item' },
  { value: 'menu', label: 'Menu Item' },
  { value: 'form', label: 'Form' },
  { value: 'module', label: 'Module' },
  { value: 'route', label: 'Route' },
  { value: 'event', label: 'Event' },
  { value: 'api', label: 'API Call' },
  { value: 'crud', label: 'CRUD Operation' },
  { value: 'widget', label: 'Dashboard Widget' },
  { value: 'action', label: 'Custom Action' },
];

export const COLLECTION_OPTIONS = [
  { value: 'users', label: 'Users' },
  { value: 'projects', label: 'Projects' },
  { value: 'nodes', label: 'Nodes' },
  { value: 'flows', label: 'Flows' },
  { value: 'students', label: 'Students' },
  { value: 'teachers', label: 'Teachers' },
  { value: 'attendance', label: 'Attendance' },
  { value: 'fees', label: 'Fees' },
  { value: 'leaves', label: 'Leaves' },
  { value: 'results', label: 'Results' },
];
