/**
 * System Design Studio — component catalog (part A).
 * CLIENTS, NETWORKING, COMPUTE, APPLICATION SERVICES.
 *
 * Every entry is a typed, semantic component definition. Type strings are
 * stable identifiers (`category.slug`) used by the backend validation engine,
 * template seeding and practice evaluation. Do not rename existing types.
 *
 * Each definition:
 *   type      — stable id, e.g. "networking.load-balancer"
 *   category  — top-level group id
 *   label     — display name
 *   description
 *   icon      — lucide icon name (resolved via lib/icons)
 *   color     — accent color
 *   size      — default node size { w, h }
 *   defaults  — default semantic properties (used by validation/practice)
 */

export const CLIENTS_COMPONENTS = [
  {
    type: 'clients.web-client',
    category: 'clients',
    label: 'Web Client',
    description: 'Browser-based client application (SPA/SSR).',
    icon: 'Globe',
    color: '#0ea5e9',
    size: { w: 200, h: 84 },
    defaults: {},
  },
  {
    type: 'clients.mobile-client',
    category: 'clients',
    label: 'Mobile Client',
    description: 'Native iOS/Android or hybrid mobile application.',
    icon: 'Smartphone',
    color: '#0ea5e9',
    size: { w: 200, h: 84 },
    defaults: {},
  },
  {
    type: 'clients.desktop-client',
    category: 'clients',
    label: 'Desktop Client',
    description: 'Desktop application (Windows/macOS/Linux).',
    icon: 'Monitor',
    color: '#0ea5e9',
    size: { w: 200, h: 84 },
    defaults: {},
  },
  {
    type: 'clients.iot-device',
    category: 'clients',
    label: 'IoT Device',
    description: 'Sensor/edge device producing telemetry or commands.',
    icon: 'Radio',
    color: '#0ea5e9',
    size: { w: 200, h: 84 },
    defaults: {},
  },
  {
    type: 'clients.external-client',
    category: 'clients',
    label: 'External Client',
    description: 'Third-party system or partner integration.',
    icon: 'ExternalLink',
    color: '#0ea5e9',
    size: { w: 200, h: 84 },
    defaults: {},
  },
  {
    type: 'clients.external-api-consumer',
    category: 'clients',
    label: 'External API Consumer',
    description: 'External consumer of your public APIs.',
    icon: 'Plug',
    color: '#0ea5e9',
    size: { w: 200, h: 84 },
    defaults: {},
  },
  {
    type: 'clients.api-consumer',
    category: 'clients',
    label: 'API Consumer',
    description: 'Service-to-service or scripted API consumer.',
    icon: 'Terminal',
    color: '#0ea5e9',
    size: { w: 200, h: 84 },
    defaults: {},
  },
];

export const NETWORKING_COMPONENTS = [
  {
    type: 'networking.internet',
    category: 'networking',
    label: 'Internet',
    description: 'Public internet entry point.',
    icon: 'Globe2',
    color: '#8b5cf6',
    size: { w: 190, h: 80 },
    defaults: {},
  },
  {
    type: 'networking.dns',
    category: 'networking',
    label: 'DNS',
    description: 'Domain name resolution (managed or self-hosted).',
    icon: 'Search',
    color: '#8b5cf6',
    size: { w: 180, h: 80 },
    defaults: { provider: 'Route53', ttlSeconds: 300 },
  },
  {
    type: 'networking.cdn',
    category: 'networking',
    label: 'CDN',
    description: 'Content delivery network for static/edge caching.',
    icon: 'Layers',
    color: '#8b5cf6',
    size: { w: 180, h: 80 },
    defaults: { edgeLocations: 30, cacheHitRatio: 85, compression: true },
  },
  {
    type: 'networking.load-balancer',
    category: 'networking',
    label: 'Load Balancer',
    description: 'Layer 4/7 traffic distribution across instances.',
    icon: 'Scale',
    color: '#8b5cf6',
    size: { w: 200, h: 84 },
    defaults: { algorithm: 'least-connections', healthChecks: true, tlsTermination: true, rateLimiting: false, stickySessions: false },
  },
  {
    type: 'networking.reverse-proxy',
    category: 'networking',
    label: 'Reverse Proxy',
    description: 'Gateway in front of services (nginx, envoy, etc.).',
    icon: 'GitCompare',
    color: '#8b5cf6',
    size: { w: 200, h: 84 },
    defaults: { rateLimiting: true, tlsTermination: true, compression: true },
  },
  {
    type: 'networking.api-gateway',
    category: 'networking',
    label: 'API Gateway',
    description: 'Single ingress for APIs: routing, auth, rate limiting.',
    icon: 'Route',
    color: '#8b5cf6',
    size: { w: 210, h: 88 },
    defaults: { rateLimitEnabled: true, authEnabled: true, tlsEnabled: true, corsEnabled: true, timeoutMs: 30000 },
  },
  {
    type: 'networking.waf',
    category: 'networking',
    label: 'WAF',
    description: 'Web application firewall filtering malicious traffic.',
    icon: 'ShieldAlert',
    color: '#8b5cf6',
    size: { w: 180, h: 80 },
    defaults: { owaspRules: true, botMitigation: true, logMode: 'block' },
  },
  {
    type: 'networking.firewall',
    category: 'networking',
    label: 'Firewall',
    description: 'Network-level access control (stateful filtering).',
    icon: 'Flame',
    color: '#8b5cf6',
    size: { w: 180, h: 80 },
    defaults: { defaultPolicy: 'deny' },
  },
  {
    type: 'networking.nat-gateway',
    category: 'networking',
    label: 'NAT Gateway',
    description: 'Outbound internet access for private resources.',
    icon: 'ArrowUpRight',
    color: '#8b5cf6',
    size: { w: 180, h: 80 },
    defaults: {},
  },
  {
    type: 'networking.service-mesh',
    category: 'networking',
    label: 'Service Mesh',
    description: 'Sidecar-based mTLS, observability and traffic control.',
    icon: 'Network',
    color: '#8b5cf6',
    size: { w: 200, h: 84 },
    defaults: { mTLS: true, retries: true, timeout: true, circuitBreaking: true },
  },
  {
    type: 'networking.vpc',
    category: 'networking',
    label: 'VPC',
    description: 'Isolated virtual private cloud network.',
    icon: 'Boxes',
    color: '#8b5cf6',
    size: { w: 200, h: 84 },
    defaults: { cidr: '10.0.0.0/16' },
  },
  {
    type: 'networking.subnet',
    category: 'networking',
    label: 'Subnet',
    description: 'Network segment (public or private).',
    icon: 'SquareStack',
    color: '#8b5cf6',
    size: { w: 190, h: 80 },
    defaults: { visibility: 'private', cidr: '10.0.1.0/24' },
  },
  {
    type: 'networking.availability-zone',
    category: 'networking',
    label: 'Availability Zone',
    description: 'Isolated data center within a region.',
    icon: 'MapPin',
    color: '#8b5cf6',
    size: { w: 200, h: 84 },
    defaults: {},
  },
  {
    type: 'networking.region',
    category: 'networking',
    label: 'Region',
    description: 'Geographic deployment region.',
    icon: 'Globe',
    color: '#8b5cf6',
    size: { w: 190, h: 80 },
    defaults: {},
  },
  {
    type: 'networking.external',
    category: 'networking',
    label: 'External Network',
    description: 'External/partner network boundary.',
    icon: 'TowerControl',
    color: '#8b5cf6',
    size: { w: 190, h: 80 },
    defaults: {},
  },
];

export const COMPUTE_COMPONENTS = [
  {
    type: 'compute.server',
    category: 'compute',
    label: 'Server',
    description: 'Application server instance.',
    icon: 'Server',
    color: '#f59e0b',
    size: { w: 200, h: 88 },
    defaults: { instances: 1, cpu: 2, memory: 4, requestsPerSec: 2000, avgLatency: 50, p95Latency: 100, p99Latency: 200, autoScaling: false },
  },
  {
    type: 'compute.virtual-machine',
    category: 'compute',
    label: 'Virtual Machine',
    description: 'Full virtual machine (EC2, Compute Engine, VM).',
    icon: 'ServerCog',
    color: '#f59e0b',
    size: { w: 200, h: 88 },
    defaults: { instances: 1, cpu: 4, memory: 16, requestsPerSec: 2000, avgLatency: 50, p95Latency: 100, p99Latency: 200, autoScaling: false },
  },
  {
    type: 'compute.container',
    category: 'compute',
    label: 'Container',
    description: 'Single container runtime instance.',
    icon: 'Container',
    color: '#f59e0b',
    size: { w: 190, h: 84 },
    defaults: { instances: 1, cpu: 1, memory: 2, requestsPerSec: 1000, avgLatency: 30, p95Latency: 70, p99Latency: 150, autoScaling: false },
  },
  {
    type: 'compute.docker-container',
    category: 'compute',
    label: 'Docker Container',
    description: 'Docker-managed container.',
    icon: 'Container',
    color: '#f59e0b',
    size: { w: 190, h: 84 },
    defaults: { instances: 1, cpu: 1, memory: 2, requestsPerSec: 1000, avgLatency: 30, p95Latency: 70, p99Latency: 150, autoScaling: false },
  },
  {
    type: 'compute.kubernetes-pod',
    category: 'compute',
    label: 'Kubernetes Pod',
    description: 'Smallest deployable unit in Kubernetes.',
    icon: 'Box',
    color: '#f59e0b',
    size: { w: 190, h: 84 },
    defaults: { instances: 1, cpu: 1, memory: 2, requestsPerSec: 1000, avgLatency: 30, p95Latency: 70, p99Latency: 150, autoScaling: false },
  },
  {
    type: 'compute.kubernetes-cluster',
    category: 'compute',
    label: 'Kubernetes Cluster',
    description: 'Cluster of nodes running containerized workloads.',
    icon: 'Boxes',
    color: '#f59e0b',
    size: { w: 220, h: 92 },
    defaults: { nodes: 3, autoScaling: true, version: '1.30' },
  },
  {
    type: 'compute.serverless-function',
    category: 'compute',
    label: 'Serverless Function',
    description: 'Event-driven function (Lambda, Cloud Functions).',
    icon: 'Zap',
    color: '#f59e0b',
    size: { w: 200, h: 88 },
    defaults: { memory: 1024, timeoutSeconds: 30, concurrency: 1000, requestsPerSec: 5000, avgLatency: 100, p95Latency: 300, p99Latency: 800 },
  },
  {
    type: 'compute.worker',
    category: 'compute',
    label: 'Worker',
    description: 'Background worker consuming from queues/streams.',
    icon: 'Cog',
    color: '#f59e0b',
    size: { w: 200, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, throughput: 5000, avgLatency: 100, p95Latency: 300, p99Latency: 600, autoScaling: true },
  },
  {
    type: 'compute.background-worker',
    category: 'compute',
    label: 'Background Worker',
    description: 'Scheduled/async job executor.',
    icon: 'Timer',
    color: '#f59e0b',
    size: { w: 200, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, throughput: 2000, avgLatency: 100, p95Latency: 300, p99Latency: 600, autoScaling: true },
  },
  {
    type: 'compute.cron-job',
    category: 'compute',
    label: 'Cron Job',
    description: 'Scheduled recurring task.',
    icon: 'CalendarClock',
    color: '#f59e0b',
    size: { w: 180, h: 80 },
    defaults: { schedule: '0 * * * *', timeoutMinutes: 60 },
  },
  {
    type: 'compute.auto-scaling-group',
    category: 'compute',
    label: 'Auto Scaling Group',
    description: 'Elastic capacity pool with scaling policies.',
    icon: 'TrendingUp',
    color: '#f59e0b',
    size: { w: 210, h: 88 },
    defaults: { minInstances: 2, maxInstances: 10, desiredInstances: 2, cpuThreshold: 70, cooldownSeconds: 300 },
  },
];

export const SERVICE_COMPONENTS = [
  {
    type: 'application-services.monolith',
    category: 'application-services',
    label: 'Monolith',
    description: 'Single deployable application unit.',
    icon: 'Building2',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 4, memory: 8, requestsPerSec: 5000, avgLatency: 50, p95Latency: 120, p99Latency: 250, autoScaling: true },
  },
  {
    type: 'application-services.microservice',
    category: 'application-services',
    label: 'Microservice',
    description: 'Independently deployable service.',
    icon: 'Blocks',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 2000, avgLatency: 50, p95Latency: 100, p99Latency: 200, autoScaling: true },
  },
  {
    type: 'application-services.auth-service',
    category: 'application-services',
    label: 'Auth Service',
    description: 'Authentication & session management.',
    icon: 'KeyRound',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 1, memory: 2, requestsPerSec: 1000, avgLatency: 40, p95Latency: 80, p99Latency: 150, autoScaling: true, tokenTtl: 3600 },
  },
  {
    type: 'application-services.user-service',
    category: 'application-services',
    label: 'User Service',
    description: 'User profiles and account management.',
    icon: 'User',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 2000, avgLatency: 40, p95Latency: 90, p99Latency: 180, autoScaling: true },
  },
  {
    type: 'application-services.payment',
    category: 'application-services',
    label: 'Payment Service',
    description: 'Payment processing and provider integrations.',
    icon: 'CreditCard',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 500, avgLatency: 80, p95Latency: 200, p99Latency: 400, autoScaling: true, idempotency: true },
  },
  {
    type: 'application-services.notification-service',
    category: 'application-services',
    label: 'Notification Service',
    description: 'Email/push/SMS notification delivery.',
    icon: 'Bell',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 1, memory: 2, requestsPerSec: 500, avgLatency: 60, p95Latency: 150, p99Latency: 300, autoScaling: true },
  },
  {
    type: 'application-services.search-service',
    category: 'application-services',
    label: 'Search Service',
    description: 'Full-text/vector search orchestration.',
    icon: 'Search',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 4, memory: 8, requestsPerSec: 3000, avgLatency: 30, p95Latency: 70, p99Latency: 150, autoScaling: true },
  },
  {
    type: 'application-services.file-service',
    category: 'application-services',
    label: 'File Service',
    description: 'Upload/download orchestration for storage.',
    icon: 'FileUp',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 500, avgLatency: 60, p95Latency: 150, p99Latency: 300, autoScaling: true, chunkedUpload: true },
  },
  {
    type: 'application-services.media-service',
    category: 'application-services',
    label: 'Media Service',
    description: 'Media processing and delivery orchestration.',
    icon: 'Video',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 4, memory: 8, requestsPerSec: 1000, avgLatency: 80, p95Latency: 200, p99Latency: 400, autoScaling: true },
  },
  {
    type: 'application-services.analytics-service',
    category: 'application-services',
    label: 'Analytics Service',
    description: 'Aggregation and analytics queries.',
    icon: 'BarChart3',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 4, memory: 8, requestsPerSec: 500, avgLatency: 200, p95Latency: 500, p99Latency: 1000, autoScaling: true },
  },
  {
    type: 'application-services.recommendation',
    category: 'application-services',
    label: 'Recommendation Service',
    description: 'Personalized content recommendations.',
    icon: 'Sparkles',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 4, memory: 8, requestsPerSec: 2000, avgLatency: 80, p95Latency: 200, p99Latency: 400, autoScaling: true },
  },
  {
    type: 'application-services.post',
    category: 'application-services',
    label: 'Post Service',
    description: 'Content/posts CRUD and timeline queries.',
    icon: 'FileText',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 5000, avgLatency: 40, p95Latency: 90, p99Latency: 180, autoScaling: true },
  },
  {
    type: 'application-services.feed',
    category: 'application-services',
    label: 'Feed Service',
    description: 'Timeline/feed generation and ranking.',
    icon: 'List',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 4, memory: 8, requestsPerSec: 5000, avgLatency: 60, p95Latency: 150, p99Latency: 300, autoScaling: true },
  },
  {
    type: 'application-services.reaction',
    category: 'application-services',
    label: 'Reaction Service',
    description: 'Likes/comments/follows handling.',
    icon: 'ThumbsUp',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 1, memory: 2, requestsPerSec: 3000, avgLatency: 30, p95Latency: 70, p99Latency: 140, autoScaling: true },
  },
  {
    type: 'application-services.dispatch',
    category: 'application-services',
    label: 'Dispatch Service',
    description: 'Dispatch/matching engine (riders, drivers, agents).',
    icon: 'Navigation',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 4, memory: 8, requestsPerSec: 1000, avgLatency: 100, p95Latency: 250, p99Latency: 500, autoScaling: true },
  },
  {
    type: 'application-services.geo',
    category: 'application-services',
    label: 'Geo Service',
    description: 'Spatial queries and geocoding (PostGIS etc.).',
    icon: 'MapPinned',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 4, memory: 8, requestsPerSec: 2000, avgLatency: 50, p95Latency: 120, p99Latency: 250, autoScaling: true },
  },
  {
    type: 'application-services.upload',
    category: 'application-services',
    label: 'Upload Service',
    description: 'Media upload intake and validation.',
    icon: 'CloudUpload',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 500, avgLatency: 80, p95Latency: 200, p99Latency: 400, autoScaling: true, chunkedUpload: true },
  },
  {
    type: 'application-services.sync',
    category: 'application-services',
    label: 'Sync Service',
    description: 'Client state synchronization and delta computation.',
    icon: 'RefreshCw',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 2000, avgLatency: 50, p95Latency: 120, p99Latency: 250, autoScaling: true, chunkedUpload: true, versioning: true, deduplication: true },
  },
  {
    type: 'application-services.catalog',
    category: 'application-services',
    label: 'Catalog Service',
    description: 'Product/content catalog management.',
    icon: 'BookOpen',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 3000, avgLatency: 40, p95Latency: 90, p99Latency: 180, autoScaling: true },
  },
  {
    type: 'application-services.cart',
    category: 'application-services',
    label: 'Cart Service',
    description: 'Shopping cart state management.',
    icon: 'ShoppingCart',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 1, memory: 2, requestsPerSec: 2000, avgLatency: 30, p95Latency: 70, p99Latency: 140, autoScaling: true },
  },
  {
    type: 'application-services.order',
    category: 'application-services',
    label: 'Order Service',
    description: 'Order lifecycle and fulfillment orchestration.',
    icon: 'Package',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 1000, avgLatency: 60, p95Latency: 150, p99Latency: 300, autoScaling: true, idempotency: true },
  },
  {
    type: 'application-services.inventory',
    category: 'application-services',
    label: 'Inventory Service',
    description: 'Stock levels, reservations and availability.',
    icon: 'Warehouse',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 1000, avgLatency: 40, p95Latency: 90, p99Latency: 180, autoScaling: true },
  },
  {
    type: 'application-services.fulfillment',
    category: 'application-services',
    label: 'Fulfillment Service',
    description: 'Shipping/fulfillment orchestration.',
    icon: 'Truck',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 500, avgLatency: 80, p95Latency: 200, p99Latency: 400, autoScaling: true },
  },
  {
    type: 'application-services.gateway',
    category: 'application-services',
    label: 'Connection Gateway',
    description: 'WebSocket/real-time connection gateway.',
    icon: 'Waypoints',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 3, connections: 500000, cpu: 2, memory: 4, autoScaling: true },
  },
  {
    type: 'application-services.push',
    category: 'application-services',
    label: 'Push Service',
    description: 'Push notification delivery (APNs/FCM).',
    icon: 'Bell',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 1, memory: 2, requestsPerSec: 500, avgLatency: 100, p95Latency: 300, p99Latency: 600, autoScaling: true },
  },
  {
    type: 'application-services.ledger',
    category: 'application-services',
    label: 'Ledger Service',
    description: 'Financial ledger with double-entry accounting.',
    icon: 'BookMarked',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 1000, avgLatency: 60, p95Latency: 150, p99Latency: 300, autoScaling: true, doubleEntry: true, idempotency: true },
  },
  {
    type: 'application-services.url-shortener',
    category: 'application-services',
    label: 'URL Shortener Service',
    description: 'Short URL creation, redirect and analytics.',
    icon: 'Link2',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 1, memory: 2, requestsPerSec: 10000, avgLatency: 20, p95Latency: 50, p99Latency: 100, autoScaling: true, uniqueAliases: true },
  },
  {
    type: 'application-services.video-service',
    category: 'application-services',
    label: 'Video Service',
    description: 'Video upload/manifest orchestration.',
    icon: 'Video',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 4, memory: 8, requestsPerSec: 500, avgLatency: 100, p95Latency: 250, p99Latency: 500, autoScaling: true },
  },
  {
    type: 'application-services.custom-service',
    category: 'application-services',
    label: 'Custom Service',
    description: 'User-defined application service.',
    icon: 'Blocks',
    color: '#6366f1',
    size: { w: 210, h: 88 },
    defaults: { instances: 2, cpu: 2, memory: 4, requestsPerSec: 2000, avgLatency: 50, p95Latency: 100, p99Latency: 200, autoScaling: true },
  },
];

export const CATALOG_PART_A = [
  ...CLIENTS_COMPONENTS,
  ...NETWORKING_COMPONENTS,
  ...COMPUTE_COMPONENTS,
  ...SERVICE_COMPONENTS,
];
