/**
 * System Design Studio — component catalog (part B).
 * DATABASES, STORAGE, MESSAGING, COMMUNICATION, SECURITY, OBSERVABILITY.
 */

export const DATABASE_COMPONENTS = [
  {
    type: 'databases.postgresql',
    category: 'databases',
    label: 'PostgreSQL',
    description: 'Relational DB (PostgreSQL) — transactions, JSON, PostGIS.',
    icon: 'Database',
    color: '#10b981',
    size: { w: 230, h: 100 },
    defaults: { version: '16', environment: 'production', mode: 'primary', replicas: 1, readsPerSec: 10000, writesPerSec: 5000, storageGB: 100, replication: 'streaming', backup: true, failover: true, multiAZ: false, consistency: 'strong', sharded: false, partitioned: false, retentionDays: 90 },
  },
  {
    type: 'databases.mysql',
    category: 'databases',
    label: 'MySQL',
    description: 'Relational DB (MySQL/MariaDB).',
    icon: 'Database',
    color: '#10b981',
    size: { w: 220, h: 96 },
    defaults: { version: '8', environment: 'production', mode: 'primary', replicas: 1, readsPerSec: 10000, writesPerSec: 5000, storageGB: 100, replication: 'binary-log', backup: true, failover: true, multiAZ: false, consistency: 'strong', sharded: false, partitioned: false, retentionDays: 90 },
  },
  {
    type: 'databases.sql-server',
    category: 'databases',
    label: 'SQL Server',
    description: 'Microsoft SQL Server.',
    icon: 'Database',
    color: '#10b981',
    size: { w: 220, h: 96 },
    defaults: { version: '2022', environment: 'production', mode: 'primary', replicas: 1, readsPerSec: 10000, writesPerSec: 5000, storageGB: 200, replication: 'always-on', backup: true, failover: true, multiAZ: false, consistency: 'strong', sharded: false, partitioned: false, retentionDays: 90 },
  },
  {
    type: 'databases.mongodb',
    category: 'databases',
    label: 'MongoDB',
    description: 'Document store (NoSQL).',
    icon: 'Database',
    color: '#10b981',
    size: { w: 220, h: 96 },
    defaults: { version: '7', environment: 'production', mode: 'replica-set', replicas: 2, readsPerSec: 20000, writesPerSec: 10000, storageGB: 200, replication: 'replica-set', backup: true, failover: true, multiAZ: false, consistency: 'eventual', sharded: false, partitioned: false, retentionDays: 90 },
  },
  {
    type: 'databases.dynamodb',
    category: 'databases',
    label: 'DynamoDB',
    description: 'Managed key-value/document DB.',
    icon: 'Database',
    color: '#10b981',
    size: { w: 220, h: 96 },
    defaults: { environment: 'production', replicas: 1, readsPerSec: 50000, writesPerSec: 50000, storageGB: 100, replication: 'multi-region', backup: true, failover: true, multiAZ: true, consistency: 'eventual', sharded: true, partitioned: true, retentionDays: 30 },
  },
  {
    type: 'databases.cassandra',
    category: 'databases',
    label: 'Cassandra',
    description: 'Wide-column distributed DB.',
    icon: 'Database',
    color: '#10b981',
    size: { w: 220, h: 96 },
    defaults: { environment: 'production', nodes: 3, replicas: 3, readsPerSec: 50000, writesPerSec: 100000, storageGB: 500, replication: 'network-topology', backup: true, failover: true, multiAZ: true, consistency: 'eventual', sharded: true, partitioned: true, retentionDays: 90 },
  },
  {
    type: 'databases.couchbase',
    category: 'databases',
    label: 'Couchbase',
    description: 'JSON document + key-value DB.',
    icon: 'Database',
    color: '#10b981',
    size: { w: 220, h: 96 },
    defaults: { environment: 'production', replicas: 1, readsPerSec: 20000, writesPerSec: 20000, storageGB: 200, replication: 'couchbase', backup: true, failover: true, multiAZ: true, consistency: 'eventual', sharded: true, partitioned: true, retentionDays: 90 },
  },
  {
    type: 'databases.neo4j',
    category: 'databases',
    label: 'Neo4j',
    description: 'Graph database.',
    icon: 'Database',
    color: '#10b981',
    size: { w: 220, h: 96 },
    defaults: { environment: 'production', replicas: 1, readsPerSec: 5000, writesPerSec: 2000, storageGB: 50, replication: 'causal', backup: true, failover: true, multiAZ: false, consistency: 'strong', sharded: false, partitioned: false, retentionDays: 90 },
  },
  {
    type: 'databases.elasticsearch',
    category: 'databases',
    label: 'Elasticsearch',
    description: 'Distributed search/analytics engine.',
    icon: 'Search',
    color: '#10b981',
    size: { w: 230, h: 100 },
    defaults: { environment: 'production', nodes: 3, replicas: 1, readsPerSec: 50000, writesPerSec: 20000, storageGB: 500, replication: 'shard-replica', backup: true, failover: true, multiAZ: false, consistency: 'eventual', sharded: true, partitioned: true, retentionDays: 90 },
  },
  {
    type: 'databases.opensearch',
    category: 'databases',
    label: 'OpenSearch',
    description: 'Open-source search/analytics suite.',
    icon: 'Search',
    color: '#10b981',
    size: { w: 230, h: 100 },
    defaults: { environment: 'production', nodes: 3, replicas: 1, readsPerSec: 50000, writesPerSec: 20000, storageGB: 500, replication: 'shard-replica', backup: true, failover: true, multiAZ: false, consistency: 'eventual', sharded: true, partitioned: true, retentionDays: 90 },
  },
  {
    type: 'databases.influxdb',
    category: 'databases',
    label: 'InfluxDB',
    description: 'Time-series database.',
    icon: 'Activity',
    color: '#10b981',
    size: { w: 220, h: 96 },
    defaults: { environment: 'production', replicas: 1, writesPerSec: 100000, storageGB: 500, replication: 'influxdb', backup: true, failover: true, multiAZ: false, consistency: 'eventual', sharded: true, partitioned: true, retentionDays: 30 },
  },
  {
    type: 'databases.timeseries',
    category: 'databases',
    label: 'Time-series Store',
    description: 'Generic time-series data store.',
    icon: 'Activity',
    color: '#10b981',
    size: { w: 220, h: 96 },
    defaults: { environment: 'production', replicas: 1, writesPerSec: 100000, storageGB: 500, backup: true, failover: true, multiAZ: false, consistency: 'eventual', sharded: true, partitioned: true, retentionDays: 30 },
  },
  {
    type: 'databases.redis',
    category: 'databases',
    label: 'Redis',
    description: 'In-memory data store / cache.',
    icon: 'Zap',
    color: '#10b981',
    size: { w: 220, h: 96 },
    defaults: { mode: 'cluster', nodes: 3, replicas: 1, requestsPerSec: 100000, memoryGB: 32, hitRatio: 90, persistence: 'RDB', eviction: 'LRU', multiAZ: true, replication: true, failover: true },
  },
  {
    type: 'databases.redis-cache',
    category: 'databases',
    label: 'Redis Cache',
    description: 'Redis used as a read/cache layer.',
    icon: 'Zap',
    color: '#10b981',
    size: { w: 220, h: 96 },
    defaults: { mode: 'cluster', nodes: 3, replicas: 1, requestsPerSec: 100000, memoryGB: 32, hitRatio: 90, persistence: 'RDB', eviction: 'LRU', multiAZ: true, replication: true, failover: true },
  },
  {
    type: 'databases.memcached',
    category: 'databases',
    label: 'Memcached',
    description: 'Distributed in-memory object cache.',
    icon: 'Zap',
    color: '#10b981',
    size: { w: 210, h: 92 },
    defaults: { mode: 'cluster', nodes: 3, requestsPerSec: 200000, memoryGB: 16, hitRatio: 85, eviction: 'LRU', multiAZ: false, replication: false },
  },
];

export const STORAGE_COMPONENTS = [
  {
    type: 'storage.object-storage',
    category: 'storage',
    label: 'Object Storage',
    description: 'Scalable object store (S3, GCS, Blob).',
    icon: 'Cloud',
    color: '#06b6d4',
    size: { w: 210, h: 88 },
    defaults: { capacityTB: 100, durability: 99.999999999, tier: 'standard', lifecycleEnabled: true, versioning: true },
  },
  {
    type: 'storage.block-storage',
    category: 'storage',
    label: 'Block Storage',
    description: 'Attached volumes for compute instances.',
    icon: 'HardDrive',
    color: '#06b6d4',
    size: { w: 200, h: 84 },
    defaults: { capacityGB: 500, iops: 3000, encrypted: true },
  },
  {
    type: 'storage.file-storage',
    category: 'storage',
    label: 'File Storage',
    description: 'Shared network file system (EFS/NFS).',
    icon: 'FolderOpen',
    color: '#06b6d4',
    size: { w: 200, h: 84 },
    defaults: { capacityTB: 1, throughputMBps: 100, encrypted: true },
  },
  {
    type: 'storage.data-lake',
    category: 'storage',
    label: 'Data Lake',
    description: 'Raw data repository for analytics.',
    icon: 'Waves',
    color: '#06b6d4',
    size: { w: 210, h: 88 },
    defaults: { capacityTB: 1000, format: 'parquet', retentionYears: 5 },
  },
  {
    type: 'storage.backup-storage',
    category: 'storage',
    label: 'Backup Storage',
    description: 'Backup/archive storage (glacier etc.).',
    icon: 'DatabaseBackup',
    color: '#06b6d4',
    size: { w: 200, h: 84 },
    defaults: { retentionDays: 365, encrypted: true, crossRegion: false },
  },
];

export const MESSAGING_COMPONENTS = [
  {
    type: 'messaging.kafka',
    category: 'messaging',
    label: 'Kafka',
    description: 'Distributed event streaming platform.',
    icon: 'GitBranch',
    color: '#f43f5e',
    size: { w: 220, h: 96 },
    defaults: { throughput: 200000, partitions: 12, replicas: 3, retentionMs: 604800000, deadLetterQueue: true, exactlyOnce: true },
  },
  {
    type: 'messaging.rabbitmq',
    category: 'messaging',
    label: 'RabbitMQ',
    description: 'AMQP message broker with routing.',
    icon: 'MessageSquare',
    color: '#f43f5e',
    size: { w: 220, h: 96 },
    defaults: { throughput: 50000, queues: 50, replicas: 3, deadLetterQueue: true },
  },
  {
    type: 'messaging.redis-streams',
    category: 'messaging',
    label: 'Redis Streams',
    description: 'Append-only log based messaging.',
    icon: 'GitCommit',
    color: '#f43f5e',
    size: { w: 220, h: 96 },
    defaults: { throughput: 50000, shards: 3, replicas: 1, deadLetterQueue: true },
  },
  {
    type: 'messaging.sqs',
    category: 'messaging',
    label: 'Amazon SQS',
    description: 'Managed message queue service.',
    icon: 'Inbox',
    color: '#f43f5e',
    size: { w: 210, h: 92 },
    defaults: { throughput: 10000, visibilityTimeout: 30, deadLetterQueue: true, fifo: false },
  },
  {
    type: 'messaging.pubsub',
    category: 'messaging',
    label: 'Pub/Sub',
    description: 'Publish/subscribe messaging.',
    icon: 'Send',
    color: '#f43f5e',
    size: { w: 210, h: 92 },
    defaults: { throughput: 100000, topics: 20, deadLetterQueue: true },
  },
  {
    type: 'messaging.event-bus',
    category: 'messaging',
    label: 'Event Bus',
    description: 'Central event routing bus.',
    icon: 'Workflow',
    color: '#f43f5e',
    size: { w: 210, h: 92 },
    defaults: { throughput: 100000, deadLetterQueue: true },
  },
  {
    type: 'messaging.message-queue',
    category: 'messaging',
    label: 'Message Queue',
    description: 'Generic message queue.',
    icon: 'MessageCircle',
    color: '#f43f5e',
    size: { w: 200, h: 88 },
    defaults: { throughput: 10000, deadLetterQueue: true },
  },
  {
    type: 'messaging.dead-letter-queue',
    category: 'messaging',
    label: 'Dead Letter Queue',
    description: 'Queue for failed/unprocessable messages.',
    icon: 'OctagonAlert',
    color: '#f43f5e',
    size: { w: 200, h: 88 },
    defaults: { throughput: 100, retentionDays: 14 },
  },
  {
    type: 'messaging.topic',
    category: 'messaging',
    label: 'Topic',
    description: 'Named channel for published events.',
    icon: 'Hash',
    color: '#f43f5e',
    size: { w: 180, h: 80 },
    defaults: { partitions: 6, replicas: 3 },
  },
  {
    type: 'messaging.consumer-group',
    category: 'messaging',
    label: 'Consumer Group',
    description: 'Group of consumers reading a stream.',
    icon: 'Users',
    color: '#f43f5e',
    size: { w: 200, h: 84 },
    defaults: { consumers: 3 },
  },
];

export const COMMUNICATION_COMPONENTS = [
  {
    type: 'communication.rest-api',
    category: 'communication',
    label: 'REST API',
    description: 'Representational state transfer API.',
    icon: 'Braces',
    color: '#14b8a6',
    size: { w: 190, h: 80 },
    defaults: { version: 'v1', auth: 'Bearer' },
  },
  {
    type: 'communication.graphql',
    category: 'communication',
    label: 'GraphQL',
    description: 'Graph query language API.',
    icon: 'Hexagon',
    color: '#14b8a6',
    size: { w: 190, h: 80 },
    defaults: { federation: false, persistedQueries: false },
  },
  {
    type: 'communication.grpc',
    category: 'communication',
    label: 'gRPC',
    description: 'High-performance RPC framework.',
    icon: 'Cable',
    color: '#14b8a6',
    size: { w: 180, h: 80 },
    defaults: { streaming: 'unary' },
  },
  {
    type: 'communication.websocket',
    category: 'communication',
    label: 'WebSocket',
    description: 'Full-duplex real-time channel.',
    icon: 'RadioTower',
    color: '#14b8a6',
    size: { w: 190, h: 80 },
    defaults: { compression: true, heartbeat: true },
  },
  {
    type: 'communication.sse',
    category: 'communication',
    label: 'SSE',
    description: 'Server-sent events stream.',
    icon: 'Radio',
    color: '#14b8a6',
    size: { w: 180, h: 80 },
    defaults: { retryMs: 3000 },
  },
  {
    type: 'communication.tcp',
    category: 'communication',
    label: 'TCP',
    description: 'Reliable stream protocol.',
    icon: 'Cable',
    color: '#14b8a6',
    size: { w: 170, h: 76 },
    defaults: {},
  },
  {
    type: 'communication.udp',
    category: 'communication',
    label: 'UDP',
    description: 'Connectionless datagram protocol.',
    icon: 'Cable',
    color: '#14b8a6',
    size: { w: 170, h: 76 },
    defaults: {},
  },
];

export const SECURITY_COMPONENTS = [
  {
    type: 'security.oauth',
    category: 'security',
    label: 'OAuth',
    description: 'OAuth 2.0 / OIDC authorization server.',
    icon: 'Fingerprint',
    color: '#ef4444',
    size: { w: 200, h: 84 },
    defaults: { grantTypes: ['authorization_code', 'client_credentials'], tokenTtl: 3600 },
  },
  {
    type: 'security.identity-provider',
    category: 'security',
    label: 'Identity Provider',
    description: 'User identity store and SSO (Okta, Auth0, IAM).',
    icon: 'UserCheck',
    color: '#ef4444',
    size: { w: 210, h: 88 },
    defaults: { sso: true, mfa: true },
  },
  {
    type: 'security.jwt',
    category: 'security',
    label: 'JWT',
    description: 'JSON Web Token signing/verification.',
    icon: 'KeyRound',
    color: '#ef4444',
    size: { w: 180, h: 80 },
    defaults: { algorithm: 'RS256', expiryMinutes: 60 },
  },
  {
    type: 'security.api-key',
    category: 'security',
    label: 'API Key',
    description: 'API key issuance and validation.',
    icon: 'Key',
    color: '#ef4444',
    size: { w: 180, h: 80 },
    defaults: { rotationDays: 90 },
  },
  {
    type: 'security.secrets-manager',
    category: 'security',
    label: 'Secrets Manager',
    description: 'Secret storage and rotation (Vault, Secrets Manager).',
    icon: 'Lock',
    color: '#ef4444',
    size: { w: 200, h: 84 },
    defaults: { autoRotation: true, encryption: 'KMS' },
  },
  {
    type: 'security.kms',
    category: 'security',
    label: 'KMS',
    description: 'Key management service for encryption.',
    icon: 'ShieldCheck',
    color: '#ef4444',
    size: { w: 190, h: 80 },
    defaults: { autoRotation: true, algorithm: 'AES-256' },
  },
  {
    type: 'security.certificate-authority',
    category: 'security',
    label: 'Certificate Authority',
    description: 'TLS certificate issuance (public or private CA).',
    icon: 'FileBadge',
    color: '#ef4444',
    size: { w: 200, h: 84 },
    defaults: { autoRenewal: true },
  },
  {
    type: 'security.rate-limiter',
    category: 'security',
    label: 'Rate Limiter',
    description: 'API rate limiting and throttling.',
    icon: 'Gauge',
    color: '#ef4444',
    size: { w: 190, h: 80 },
    defaults: { tiers: 'yes', http429: true, algorithm: 'token-bucket' },
  },
];

export const OBSERVABILITY_COMPONENTS = [
  {
    type: 'observability.logging',
    category: 'observability',
    label: 'Logging',
    description: 'Centralized log collection and search.',
    icon: 'FileText',
    color: '#f97316',
    size: { w: 200, h: 84 },
    defaults: { retentionDays: 30, level: 'info' },
  },
  {
    type: 'observability.metrics',
    category: 'observability',
    label: 'Metrics',
    description: 'Time-series metrics collection (Prometheus etc.).',
    icon: 'Gauge',
    color: '#f97316',
    size: { w: 200, h: 84 },
    defaults: { retentionDays: 30, scrapeInterval: 15 },
  },
  {
    type: 'observability.distributed-tracing',
    category: 'observability',
    label: 'Distributed Tracing',
    description: 'End-to-end request tracing (Jaeger, Zipkin).',
    icon: 'Waypoints',
    color: '#f97316',
    size: { w: 210, h: 88 },
    defaults: { samplingRate: 10 },
  },
  {
    type: 'observability.monitoring',
    category: 'observability',
    label: 'Monitoring',
    description: 'Dashboards and health monitoring.',
    icon: 'BarChart3',
    color: '#f97316',
    size: { w: 200, h: 84 },
    defaults: { retentionDays: 90 },
  },
  {
    type: 'observability.alerting',
    category: 'observability',
    label: 'Alerting',
    description: 'Alert rules and notification routing.',
    icon: 'BellRing',
    color: '#f97316',
    size: { w: 190, h: 80 },
    defaults: { channels: ['email', 'slack', 'pagerduty'] },
  },
  {
    type: 'observability.siem',
    category: 'observability',
    label: 'SIEM',
    description: 'Security event monitoring and correlation.',
    icon: 'Radar',
    color: '#f97316',
    size: { w: 190, h: 80 },
    defaults: { retentionDays: 365 },
  },
];

export const CATALOG_PART_B = [
  ...DATABASE_COMPONENTS,
  ...STORAGE_COMPONENTS,
  ...MESSAGING_COMPONENTS,
  ...COMMUNICATION_COMPONENTS,
  ...SECURITY_COMPONENTS,
  ...OBSERVABILITY_COMPONENTS,
];
