/**
 * SQL DDL Code Generator for ER Diagram Studio.
 * Generates SQL scripts for: PostgreSQL, MySQL, SQLite, SQL Server, and Oracle.
 */

export function generateSQL(tables = [], relationships = [], dialect = 'postgresql') {
  if (!tables.length) return '-- No tables defined in model.\n';

  let sql = `-- Database Schema DDL (${dialect.toUpperCase()})\n`;
  sql += `-- Generated on ${new Date().toISOString().split('T')[0]}\n\n`;

  // ── Helper to map types based on database dialect ──
  const mapType = (type, isIncrement = false) => {
    const t = type.toLowerCase();
    
    switch (dialect) {
      case 'mysql':
      case 'mariadb':
        if (isIncrement) return 'INT AUTO_INCREMENT';
        if (t.startsWith('integer') || t === 'int') return 'INT';
        if (t === 'string' || t === 'varchar') return 'VARCHAR(255)';
        if (t === 'text') return 'TEXT';
        if (t === 'timestamp' || t === 'datetime') return 'DATETIME';
        if (t === 'boolean') return 'TINYINT(1)';
        return type;

      case 'sqlite':
        if (isIncrement) return 'INTEGER PRIMARY KEY AUTOINCREMENT';
        if (t.startsWith('integer') || t === 'int') return 'INTEGER';
        if (t === 'string' || t === 'varchar' || t === 'text') return 'TEXT';
        if (t === 'timestamp' || t === 'datetime') return 'TEXT';
        if (t === 'boolean') return 'INTEGER';
        return type;

      case 'sqlserver':
        if (isIncrement) return 'INT IDENTITY(1,1)';
        if (t.startsWith('integer') || t === 'int') return 'INT';
        if (t === 'string' || t === 'varchar') return 'VARCHAR(255)';
        if (t === 'text') return 'VARCHAR(MAX)';
        if (t === 'timestamp' || t === 'datetime') return 'DATETIME2';
        if (t === 'boolean') return 'BIT';
        return type;

      case 'oracle':
        if (isIncrement) return 'NUMBER GENERATED BY DEFAULT AS IDENTITY';
        if (t.startsWith('integer') || t === 'int') return 'NUMBER(10)';
        if (t === 'string' || t === 'varchar') return 'VARCHAR2(255)';
        if (t === 'text') return 'CLOB';
        if (t === 'timestamp' || t === 'datetime') return 'TIMESTAMP';
        if (t === 'boolean') return 'NUMBER(1)';
        return type;

      case 'postgresql':
      default:
        if (isIncrement) return 'SERIAL';
        if (t.startsWith('integer') || t === 'int') return 'INTEGER';
        if (t === 'string' || t === 'varchar') return 'VARCHAR(255)';
        if (t === 'text') return 'TEXT';
        if (t === 'timestamp' || t === 'datetime') return 'TIMESTAMP';
        if (t === 'boolean') return 'BOOLEAN';
        return type;
    }
  };

  // ── Create Tables ──
  tables.forEach((table) => {
    sql += `CREATE TABLE ${table.name} (\n`;
    
    const columnsSQL = table.fields.map((field) => {
      let colDef = `  ${field.name} `;

      // In SQLite, if it is increment, the primary key must be inline on the column definition
      const isSqliteIncrement = dialect === 'sqlite' && field.isIncrement;
      
      colDef += mapType(field.type, field.isIncrement);

      if (field.isPk && !isSqliteIncrement) {
        colDef += ' PRIMARY KEY';
      }
      
      if (!field.isNullable) {
        colDef += ' NOT NULL';
      }

      if (field.isUnique) {
        colDef += ' UNIQUE';
      }

      if (field.defaultVal) {
        // Simple default parsing
        const isString = ['varchar', 'string', 'text'].includes(field.type.toLowerCase());
        const quote = isString ? "'" : '';
        colDef += ` DEFAULT ${quote}${field.defaultVal}${quote}`;
      }

      return colDef;
    });

    sql += columnsSQL.join(',\n');
    sql += '\n);\n\n';
  });

  // ── Add Foreign Key Constraints (Skip for SQLite as it requires inline definition or special setup) ──
  if (dialect !== 'sqlite' && relationships.length) {
    sql += `-- Foreign Key Constraints\n`;
    relationships.forEach((rel) => {
      const constraintName = `fk_${rel.fromTable}_${rel.fromField}`;
      sql += `ALTER TABLE ${rel.fromTable}\n`;
      sql += `  ADD CONSTRAINT ${constraintName}\n`;
      sql += `  FOREIGN KEY (${rel.fromField}) REFERENCES ${rel.toTable} (${rel.toField})\n`;
      sql += `  ON DELETE CASCADE;\n\n`;
    });
  }

  // ── Add Basic Indexes on Foreign Keys (Recommended for performance) ──
  if (relationships.length) {
    sql += `-- Indexes on Foreign Keys\n`;
    relationships.forEach((rel) => {
      sql += `CREATE INDEX idx_${rel.fromTable}_${rel.fromField} ON ${rel.fromTable}(${rel.fromField});\n`;
    });
    sql += `\n`;
  }

  return sql;
}
